from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Dict, Union

import pandas as pd

from reamber.base.Map import Map
from reamber.quaver.QuaMapMeta import QuaMapMeta
from reamber.quaver.lists.QuaBpmList import QuaBpmList
from reamber.quaver.lists.QuaSvList import QuaSvList
from reamber.quaver.lists.notes.QuaHitList import QuaHitList
from reamber.quaver.lists.notes.QuaHoldList import QuaHoldList
from reamber.quaver.lists.notes.QuaNoteList import QuaNoteList


@dataclass
class QuaMap(Map[QuaNoteList, QuaHitList, QuaHoldList, QuaBpmList], QuaMapMeta):

    _props = dict(svs=QuaSvList)

    @property
    def svs(self) -> QuaSvList: ...
    @svs.setter
    def svs(self, val) -> None: ...
    @staticmethod
    def read(lines: Union[List[str], str], safe: bool = True) -> QuaMap: ...
    @staticmethod
    def read_file(file_path: str) -> QuaMap: ...
    def write(self) -> str: ...
    def write_file(self, file_path: str) -> None: ...
    def _read_bpms(self, bpms: List[Dict]) -> None: ...
    def _read_svs(self, svs: List[Dict]) -> None: ...
    def _read_notes(self, notes: List[Dict]) -> None: ...
    def scroll_speed(self, center_bpm: float = None) -> List[Dict[str, float]]: ...
    # noinspection PyMethodOverriding
    def metadata(self, unicode=True) -> str: ...
    def rate(self, by: float): ...

    class Stacker(Map.Stacker):
        @property
        def keysounds(self) -> pd.Series: ...
        @keysounds.setter
        def keysounds(self, val) -> None: ...

    @property
    def stack(self) -> Stacker: ...
