from __future__ import annotations

from reamber.base.Timed import Timed


class OsuSample(Timed):
    def __init__(self, offset: float, sample_file:str = '', volume: int = 70, **kwargs): ...
    @staticmethod
    def read_string(s: str) -> OsuSample: ...
    def write_string(self) -> str: ...
    @property
    def sample_file(self) -> str: ...
    @sample_file.setter
    def sample_file(self, val) -> None: ...
    @property
    def volume(self) -> str: ...
    @volume.setter
    def volume(self, val) -> None: ...